from datetime import datetime

from sqlmodel import SQLModel, Field


class EventBase(SQLModel): # Common attributes
    title: str
    description: str
    date: datetime
    location: str

class Event(EventBase, table=True): # Class for ORM
    id:int = Field(default=None, primary_key=True) # The ID is automatically generated by the DB.


class EventPublic(EventBase): # Class used for showing events
    id:int


class EventCreate(EventBase): # Class used to create events
    pass